
#
# This file is part of the PoCs for various issues found in the cryptographic
# design of Mega.
#
# Content: constants as specified by Mega's cryptographic implementation
#

RSA_MODULUS_BIT_SIZE = 2048
RSA_MODULUS_BYTE_SIZE = 256
RSA_PUBLIC_EXP = 0x10001
SID_LEN = 43
SID_BIT_LEN = SID_LEN * 8

AES_BLOCK_BYTE_SIZE = 16
AES_BLOCK_BIT_SIZE = AES_BLOCK_BYTE_SIZE * 8
PREFIX_MIN_BYTE_LEN = 1
PREFIX_MIN_BIT_LEN = PREFIX_MIN_BYTE_LEN * 8
PREFIX_MAX_BYTE_LEN = 2
PREFIX_MAX_BIT_LEN = PREFIX_MAX_BYTE_LEN * 8

LEN_ENCODING_BYTE_LEN = 2
LEN_ENCODING_BIT_LEN = LEN_ENCODING_BYTE_LEN * 8

# Number of bits enforced by the length check oracle of RSA chat key decryption
RSA_ORACLE_MOD_BITS = 4

MASTER_KEY_BYTE_LEN = 16
MASTER_KEY_BIT_LEN = MASTER_KEY_BYTE_LEN * 8

NODE_KEY_BYTE_LEN = 16
NODE_KEY_BIT_LEN = NODE_KEY_BYTE_LEN * 8

CHAT_KEY_BYTE_LEN = 16
CHAT_KEY_BIT_LEN = CHAT_KEY_BYTE_LEN * 8

OBF_NODE_KEY_BYTE_LEN = 32
OBF_NODE_KEY_BIT_LEN = OBF_NODE_KEY_BYTE_LEN * 8

FILE_NONCE_BYTE_LEN = 8
FILE_NONCE_BIT_LEN = 64

FILE_CHUNK_BYTE_SIZE = 131072 # 128 KB
FILE_CHUNK_BIT_SIZE = FILE_CHUNK_BYTE_SIZE * 8
FILE_AES_BLOCKS_PER_CHUNK = FILE_CHUNK_BYTE_SIZE // AES_BLOCK_BYTE_SIZE

FILE_HANDLE_BYTE_LEN = 6
FILE_HANDLE_BIT_LEN = FILE_HANDLE_BYTE_LEN * 8
